server:
  port: 8130
  
# application
spring:
  application:
    name: gateway-zuul-filter
    
    
# eureka
eureka:
  client:
    healthcheck:
      enable: true
    service-url: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka/
  instance:
    # default use ip
    prefer-ip-address: true
    # 应用名称[ip:port] => ${spring.application.name} [${spring.cloud.client.ipAddress}:${server.port}]
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
    # 配置允许的应用服务映射
    provider-user: /user/**
    # consumer-mo，多个以都好分隔
  # ignored-services: consumer-movie-ribbon-with-hystrix
  # 或者
  ignored-services: '*'
  
management:
  security:
    enabled:  false
    
# 禁用过滤器
# zuul.PreZuulFilter.pre.disable: true