server:
  port: 8114
  
# application
spring:
  application:
    name: hystrix-turbine-urlsuffix

# eureka config
eureka:
  client:
    serviceUrl: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka
  instance:
    # default use ip
    prefer-ip-address: true
    # 应用名称[ip:port] => ${spring.application.name} [${spring.cloud.client.ipAddress}:${server.port}]
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

# turbin配置
turbine:
  aggregator:
    clusterConfig: CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX-TURBINE-URLSUFFIX
  appConfig: consumer-movie-ribbon-with-hystrix-turbine-urlsuffix
  # turbine的urlsuffix配置
  instanceUrlSuffix:
    CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX-TURBINE-URLSUFFIX: /ribbon/hystrix.stream 
logging:
  level: 
    root: info
    com.netflix.turbine.monitor: debug

