server:
  port: 8111
spring:
  application:
    name: consumer-movie-ribbon-with-hystrix
eureka:
  client:
    serviceUrl: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka
  instance:
    prefer-ip-address: true 
    # 应用名称[ip:port] => ${spring.application.name} [${spring.cloud.client.ipAddress}:${server.port}]
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
# 设定时间  
# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
    