server:
  port: 8098
spring:
  application:
    name: consumer-movie-ribbon-without-eureka
eureka:
  client:
    serviceUrl: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka
  instance:
    prefer-ip-address: true
    # 应用名称[ip:port] => ${spring.application.name} [${spring.cloud.client.ipAddress}:${server.port}]
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
# 禁用eureka的ribbon
ribbon:
   eureka:
    enable: false
# 选用ribbon提供者
provider-user:
  ribbon:
    listOfServers: localhost:8090