server:
  port: 9010
spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/lolog/cloud-config
          search-paths: 
            - ro
            - to
  # rabbitmq配置
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password:  guest

# 步骤
# 1. 添加注解
# 2. 修改git仓库
# 3. curl -X POST http://localhost:9013/bus/refresh # 手动批量刷新

# 自动刷新：可以通过设置git
# 最好配置在config server中

# 注册到eureka          
eureka:
  client:
    serviceUrl: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}