server:
  port: 8090
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:datas.sql
  application:
    name: provider-user # lower letter
logging:
  level: debug
  org.hibernate: info
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  net.yeah.cloud: debug

# eureka config
eureka:
  client:
    serviceUrl: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka
  instance:
    # default use ip
    prefer-ip-address: true
    # 应用名称[ip:port] => ${spring.application.name} [${spring.cloud.client.ipAddress}:${server.port}]
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}