server:
  port: 8126
# 关闭security验证
# /routes为代理服务
management.security.enabled: false
spring:
  application:
    name: gateway-zuul-hystrix-fallback-route
# eureka
eureka:
  client:
    healthcheck:
      enable: true
    service-url: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka/
  instance:
    # default use ip
    prefer-ip-address: true
    # 应用名称[ip:port] => ${spring.application.name} [${spring.cloud.client.ipAddress}:${server.port}]
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
# header配置
zuul:
  routes: 
    usr: # http://localhost:8125/user-route/provider/find/1
      path: /user-route/**
      serviceId: provider-user
