server:
  port: 8100
spring:
  application:
    name: consumer-movie-feign-customizing
eureka:
  client:
    serviceUrl: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka
  instance:
    prefer-ip-address: true
    # 应用名称[ip:port] => ${spring.application.name} [${spring.cloud.client.ipAddress}:${server.port}]
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
# feign logging
# 1. 修改配置文件
# 2. 修改 configuration 类
logging:
  level: 
    net.yeah.cloud.movie.feign.UserFeignClient: debug