server:
  port: 8113
  # 配置之后，请求的地址必须加上/ribbon
  context-path: /ribbon
spring:
  application:
    name: consumer-movie-ribbon-with-hystrix-turbine-urlsuffix
eureka:
  client:
    serviceUrl: 
      defaultZone: http://lolog:lolog@localhost:8092/eureka
  instance:
    prefer-ip-address: true
    home-page-url-path: /ribbon
    # 应用名称[ip:port] => ${spring.application.name} [${spring.cloud.client.ipAddress}:${server.port}]
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
   
# 设定时间  
# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
    