server:
  port: 9011

# 注意healthcheck只能配置到application中，如果配置到bootstrap中，
# 将会出现UNKONWN现象
eureka.client.healthcheck.enabled: true

#spring:
#  application:
#    name: foo
#  cloud:
#    config:
#      uri: http://localhost:9000
#      profile: deb
#      # 当config-server后端是git时
#      label: master

# 报错 => Fetching config from server at: http://localhost:8888
#         Could not resolve placeholder 'profile' in value "${profile}"
# 加载次序 =>
# bootstrap.*  -> 连接config server,加载远程配置 -> application.*
# 因此spring config需要配置在bootstrap里面